app.py
from main import create_app, socketio
import os

app = create_app()

if __name__ == '__main__':
    if app.config['PORT']:
        port = app.config['PORT']
    else:
        port = int(os.environ.get('PORT', 8080))
    socketio.run(app, host='0.0.0.0', port=port,  allow_unsafe_werkzeug=True)


controllers/api/v1/__init__.py
from flask import Blueprint
from controllers.api.v1.ping import ping
from controllers.api.v1.data_handler import data_handler
from controllers.api.v1.demo_handler import *

version_1_controller = Blueprint('version_1_controller', __name__, url_prefix="/api/v1")
version_1_controller.register_blueprint(ping)
version_1_controller.register_blueprint(data_handler)

controllers/view_controller.py
from flask import Blueprint, render_template, request, redirect

from services.mongo_service import get_by_collection_with_page, get_collection_list, get_collection_page_size, get_collection_expain, insert_one_to_collection
from utils import get_adjust_pagination

view_controller = Blueprint('view_controller', __name__, template_folder='templates')


@view_controller.route('/')
def index():
    return render_template(f'pages/home.html')
    

@view_controller.route('/collections')
def collections():
    return render_template(f'pages/collections.html')

@view_controller.route('/detail/<collection>')
def detail(collection):
    page_num = request.args.get('page')
    if not page_num:
        return redirect(f"/detail/{collection}?page=1")
    page_num = int(page_num)
    data = get_by_collection_with_page(collection, page_num)
    count = get_collection_page_size(collection)
    pagination = get_adjust_pagination(count, page_num)
    fields = get_collection_expain(collection)
    result = {"title": collection, "data": data, "pagination": pagination, "current_page": page_num, "fields": fields}

    return render_template(f'pages/detail.html', result=result)

@view_controller.route('/add/<collection>', methods = ['GET', 'POST', 'DELETE'])
def add(collection):
    fields = get_collection_expain(collection)
    if request.method == 'GET':
        return render_template(f'pages/add.html', data={"fields": fields, "title": collection})
    elif request.method == 'POST':
        data_dict = {}
        for field in fields:
            if field != "_id":
                input_data = request.form.get(field)
                if input_data == '':
                    data_dict[field] = None
                else:
                    data_dict[field] = input_data
        print(data_dict)
        insert_one_to_collection(collection, data_dict)
        return redirect('/collections?message=Successfully insert a data')
    else:
        print(request.method)
        return redirect('/collections')
    

@view_controller.route('/demo/<collection>')
def demo(collection):
    collections = get_collection_list()

    if not collection in collections:
        raise Exception(f"Unable to find {collection} in database")
    result = {
        "title": collection
    }
    return render_template(f'pages/demo.html', data=result)

main.py
#----------------------------------------------------------------------------#
# Imports
#----------------------------------------------------------------------------#

from flask import Flask, render_template
from flask_socketio import SocketIO

import logging
from logging import Formatter, FileHandler

import os

from database import MongoJsonEncoder

socketio = SocketIO(cors_allowed_origins="*")

def create_app():

    #----------------------------------------------------------------------------#
    # App Config.
    #----------------------------------------------------------------------------#

    app = Flask(__name__)
    app.config.from_pyfile('config.py') # this config for the basic application setup

    # Mongodb connection
    app.config['MONGO_URI'] = os.getenv('MONGO_URI')

    # For decoding the bson object
    app.json_provider_class = MongoJsonEncoder

    #----------------------------------------------------------------------------#
    # Controllers.
    #----------------------------------------------------------------------------#


    #-------------------------------------------------------#
    # Imports
    #-------------------------------------------------------#

    from controllers.view_controller import view_controller
    from controllers.api.v1 import version_1_controller

    #-------------------------------------------------------#
    # Registers
    #-------------------------------------------------------#

    app.register_blueprint(view_controller)

    # Version 1
    app.register_blueprint(version_1_controller)

    # Error handlers.
    @app.errorhandler(500)
    def internal_error(error):
        #db_session.rollback()
        return render_template('errors/500.html'), 500

    @app.errorhandler(404)
    def not_found_error(error):
        return render_template('errors/404.html'), 404

    @app.errorhandler(Exception)
    def handle_exception(e):
        # pass through HTTP errors
        print(e)
        # now you're handling non-HTTP exceptions only
        return render_template("errors/500.html", e=e), 500

    if not app.debug:
        file_handler = FileHandler('error.log')
        file_handler.setFormatter(
            Formatter('%(asctime)s %(levelname)s: %(message)s [in %(pathname)s:%(lineno)d]')
        )
        app.logger.setLevel(logging.INFO)
        file_handler.setLevel(logging.INFO)
        app.logger.addHandler(file_handler)
        app.logger.info('errors')

    #----------------------------------------------------------------------------#
    # Launch.
    #----------------------------------------------------------------------------#

    # Or specify port manually:

    socketio.init_app(app)
    return app



templates/layouts/main.html
<!doctype html>
<html lang="en" data-bs-theme="dark">
  <head>
  <meta charset="utf-8">
  <title>{% block title %}{% endblock %}</title>

  <!-- meta -->
  <meta name="description" content="">
  <meta name="author" content="">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <!-- /meta -->

  <!-- styles -->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.4/font/bootstrap-icons.css">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
  <link type="text/css" rel="stylesheet" href="/static/css/layout.main.css" />
  <link type="text/css" rel="stylesheet" href="/static/css/main.css" />
  <!-- /styles -->

  <!-- favicons -->
  <link rel="shortcut icon" href="/static/ico/favicon.png">
  <link rel="apple-touch-icon-precomposed" sizes="144x144" href="/static/ico/apple-touch-icon-144-precomposed.png">
  <link rel="apple-touch-icon-precomposed" sizes="114x114" href="/static/ico/apple-touch-icon-114-precomposed.png">
  <link rel="apple-touch-icon-precomposed" sizes="72x72" href="/static/ico/apple-touch-icon-72-precomposed.png">
  <link rel="apple-touch-icon-precomposed" href="/static/ico/apple-touch-icon-57-precomposed.png">
  <link rel="shortcut icon" href="/static/ico/favicon.png">
  <!-- /favicons -->

  </head>
  <body>

    <!-- Wrap all page content here -->
    <div id="wrap">

      <!-- Fixed navbar -->
      <nav class="navbar navbar-expand-lg bg-body-tertiary">
        {% include  'layouts/nav.html' %}
      </nav>
      <!-- Begin page content -->
      <main id="content" role="main" class="container">

        <div id="liveAlertPlaceholder"></div>
        {% block content %}{% endblock %}
        
      </main>

    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/socket.io/4.0.1/socket.io.js" integrity="sha512-q/dWJ3kcmjBLU4Qc47E4A9kTB4m3wuTY7vkFJDTZKjTs8jhyGQnaUrxa0Ytd0ssMZhbNua9hE+E7Qv1j+DyZwA==" crossorigin="anonymous"></script>
    <script type="module" src="/static/js/general.js" defer></script>
  </body>
</html>

templates/layouts/nav.html
<div class="container-fluid">
    <a class="navbar-brand" href="{{ url_for('view_controller.index') }}">Group 18</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link {% if request.endpoint == 'view_controller.index' %} active {% endif %}" aria-current="page" href="{{ url_for('view_controller.index') }}">Home</a>
        </li>
        <li class="nav-item">
            <a class="nav-link {% if request.endpoint == 'view_controller.collections' %} active {% endif %}" href="{{ url_for('view_controller.collections') }}">Demo</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="http://uwaterloo.eastus.cloudapp.azure.com:8000/">Classification</a>
        </li>
    </ul>
    </div>
</div>
  

templates/pages/add.html
{% extends 'layouts/main.html' %}
{% block title %}Add{% endblock %}
{% block content %}

<div class="container">
  <div class="row">
    <h1>{{ data.title }}</h1>
  </div>
  <br>

  <div class="row">
    <p>You can add one data to a dataset.</p>
  </div>

  <div class="row">
    <hr style="margin-bottom: 60px;"/>
  </div>

  <form method="post" class="form">
    {% for field in data.fields %}
      {% if field != '_id' %}
      <div class="row">
        <div class="input-group mb-3">
          <input type="text" class="form-control" name="{{ field }}" aria-label="{{ field }}" aria-describedby="{{ field }}">
          <span class="input-group-text" id="{{ field }}">{{ field }}</span>
        </div>
      </div>
      {% endif %}
    {% endfor %}
    <div class="row" style="padding: 20px; margin-top: 20px;">
      <button type="submit" class="btn btn-primary">Add</button>
    </div>
  </form>
</div>




{% endblock %}

templates/pages/collections.html
{% extends 'layouts/main.html' %}
{% block title %}Demo Collections{% endblock %}
{% block content %}

<div class="container">
  <div class="row justify-content-between align-items-center">
    <div class="col-8">
      <h1>
        Demo Collections
      </h1>
    </div>
    <div class="col-4 text-end">
        <button id="upload_modal_toggle" type="button" class="btn btn-primary col-12 col-md-4" data-bs-toggle="modal" data-bs-target="#upload_modal">
          Upload
        </button>

        <button id="refresh" type="button" class="btn btn-primary col-5 col-md-2" onclick="window.reload_collections()">
          <i class="bi bi-arrow-repeat"></i>
        </button>
    </div>
  </div>

  <br>

  <div class="row">
    <p>Upload the csv file and register it in the database.
      Files of the same name are extended to existing data.</p>
  </div>

  <div class="row">
    <hr style="margin-bottom: 60px;"/>
  </div>
</div>

<table class="table">
  <thead>
    <tr>
      <th class="col-1" scope="col">#</th>
      <th class="col-6" scope="col">Collection Name</th>
      <th class="col-5 text-end" scope="col">Actions</th>
    </tr>
  </thead>
  <tbody id="collection-target" class="table-group-divider"><tr></tr></tbody>
</table>

<!-- Modal -->
<div class="modal fade" id="upload_modal" tabindex="-1" aria-labelledby="upload_file" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="upload_file">Upload file to collections</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <form method="post" class="form insert_by_file" enctype="multipart/form-data">
        <div class="modal-body">
            <div>
              <label for="formFile" class="form-label">file input</label>
              <input autofocus class="form-control form-control-lg" id="formFile" name="file" type="file" required>
            </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
          <button type="submit" class="btn btn-primary">Upload</button>
        </div>
      </form>
    </div>
  </div>
</div>

<script type="module" src="/static/js/collections.js"></script>

{% endblock %}

templates/pages/demo.html
{% extends 'layouts/main.html' %}
{% block title %}Demo{% endblock %}
{% block content %}

<div class="container">
  <div class="row text-center">
    <h1 style="word-break:break-word;">{{ data.title }}</h1>
    <hr style="margin-bottom: 60px;"/>
  </div>
</div>

<div id="ml-progress" class="container">

</div>

<script type="module" src="/static/js/demo.js"></script>

{% endblock %}

templates/pages/detail.html
{% extends 'layouts/main.html' %}
{% block title %}Detail{% endblock %}
{% block content %}
<div class="container">
    <div class="row">
        <h1>{{ result.title }}</h1>
    </div>
    <br>

    <div class="row">
        <p>All datasheets imported from MongoDB.</p>
    </div>

    <div class="row">
        <hr style="margin-bottom: 60px;"/>
    </div>

    <div class="row">
        <div class="table-responsive">
            <table class="table table-dark">
                <thead>
                <tr>
                    {% for field in result['fields'] %}
                        <th scope="col">{{ field }}</th>
                    {% endfor %}
                </tr>
                </thead>
                <tbody class="table-group-divider">
                {% for row in result['data'] %}
                    <tr>
                    {% for field in result['fields'] %}
                        {% if field == '_id' %}
                            <th scope="row">{{ row['_id'] }}</th>
                        {% else %}
                            <td>{{ row[field] }}</td>
                        {% endif %}
                    {% endfor %}
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>

    <div class="row" style="margin-top: 20px;">
        <nav aria-label="Page navigation example">
            <ul class="pagination justify-content-center pagination-sm">
                {% for page_number in result.pagination %}
                    <li class="page-item {% if page_number == result.current_page %} active {% endif %} {% if page_number == '...' %} disabled {% endif %}'">
                        <a class="page-link" {% if page_number != "..." %} href="?page={{ page_number }} {% endif %}">
                            {{ page_number }}
                        </a>
                    </li>
                {% endfor %}
            </ul>
        </nav>
    </div>
</div>
{% endblock %}

templates/pages/home.html
{% extends 'layouts/main.html' %}
{% block title %}Home{% endblock %}
{% block content %}

<div class="container text-center">
  <div class="row p-2">
    <p class="lead">
      <em>Big Data Management Systems and Tools</em>
    </p>
  </div>
  <div class="row p-3">
    <h1>Supporting the prediction of geological domain units for gold exploration</h1>
  </div>
  
  <div class="row p-3 justify-content-center">
    <div class="col-md-4 col-10">
      <table class="table">
        <tbody>
          <tr>
            <td>Fernando Lopez</td>
          </tr>
          <tr>
            <td>Maria Adelaida Fernandez</td>
          </tr>
          <tr>
            <td>Ihab El Attar</td>
          </tr>
          <tr>
            <td>Samina Warraich</td>
          </tr>
          <tr>
            <td>Azadeh Naghibi</td>
          </tr>
          <tr>
            <td>Aaron Wooseok Lee</td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>

  <div class="row p-2">
    <p>Group 18</p>
  </div>
</div>

<br>

<div class="container">
  <div class="row justify-content-center">
      <a role="button" class="btn btn-primary col-5 col-md-3 right-space" href="/collections">Demo</a>
      <a role="button" class="btn btn-primary col-5 col-md-3" href="http://uwaterloo.eastus.cloudapp.azure.com:8000/">Get Classification</a>
  </div>
</div>

<br><br>

<div class="container">
  <div class="row">
    <h2 class="lead">Project Topic:</h2>
  </div>
  <div class="row">
    <p>
      Build, finetune and deploy a Machine Learning model application using unsupervised clustering analysis to predict geological domain units from laboratory sample geochemistry.
    </p>
  </div>
</div>

<br><br>

<div class="container">
  <div class="row">
    <h2 class="lead">Dataset:</h2>
  </div>
  <div class="row">
    <p>
      The data consists of laboratory geochemistry analysis performed on continuous rock samples obtained from drilling. 
      These samples belong to the TUL exploration project in Manitoba.
      Samples and results are stored in the Assay table which will be used to create the ML model.
    </p>
  </div>
  <div class="row p-2">
    <div class="col-12">
      <table class="table">
        <thead>
          <tr>
            <th scope="col"></th>
            <th scope="col">ASSAY TABLE</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <th scope="row">Description</th>
            <td>
              Laboratory results grouped by drillhole number (HOLEID) and analyzed interval (SAMPFROM - SAMPTO).
              It contains 96 columns with geochemical results for each sampled interval (SAMPLEID).
            </td>
          </tr>
          <tr>
            <th scope="row">Size</th>
            <td>
              12648 rows x 96 columns
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
  <div class="row p-2 justify-content-center">
    <img class="col-10 col-md-8" src="/static/img/example.png"/>
  </div>
</div>

<br><br>

<div class="container">
  <div class="row">
    <h2 class="lead">Objective:</h2>
  </div>
  <div class="row">
    <p>
      The main objective of the project is to build an application to support geologists with the identification of rock types 
      (lithology) in their exploration areas. 
      This application will (1) speed up the geological logging process and (2) provide qualitative information for the project. 
    </p>
    <p>
      To build the application, the best machine learning model will be trained and tested using a subsample of the existing dataset, 
      using a refined pipeline and hyperparameter tuning in Spark (Databricks), 
      to cluster future drilling samples and support the identification of areas better suited for gold exploration and mining. 
      Once the pipeline is created, options for packaging the model and deploying it will be explored, 
      including creating widgets on Databricks and building a front end using Flask.
    </p>
  </div>
</div>

<br><br>

<div class="container text-center">
  <div class="row">
    <h2 class="lead">Workflow:</h2>
  </div>
  <div class="row justify-content-center">
    <img class="col-10 col-md-4" style="height: 100%;" src="/static/img/workflow.png"/>
  </div>
  <br>
  <div class="row p-2">
    <p>
      An application will be created with the best ML model for deployment.
    </p>
  </div>
</div>

<br><br><br>

<div class="container">
  <div class="row justify-content-center">
      <a role="button" class="btn btn-primary col-5 col-md-3 right-space" href="/collections">Demo</a>
      <a role="button" class="btn btn-primary col-5 col-md-3" href="http://uwaterloo.eastus.cloudapp.azure.com:8000/">Get Classification</a>
  </div>
</div>

<br><br>

{% endblock %}

templates/pages/predict.html
{% extends 'layouts/main.html' %}
{% block title %}Predict{% endblock %}
{% block content %}

<div class="container">
  <div class="row text-center">
    <h1>{{ data.title }}</h1>
    <hr style="margin-bottom: 60px;"/>
  </div>

</div>

{% endblock %}